<?php

/**
 * @Entity(repositoryClass="ArticleRepository") @Table(name="article") @HasLifecycleCallbacks 
 */
class Article
{
    use ActiveEntity;
    use Timestampable;
    use SerializableEntity;

    /**
     * @Id @Column(type="integer") @GeneratedValue
     */
    protected $id;
    
    /**
     * @Column(type="string")
     */
    protected $title;
    
    /**
     * @Column(type="string")
     */
    protected $content;
}

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends Doctrine\ORM\EntityRepository
{
}
