<?php

/**
 * @Entity(repositoryClass="ArticleRepository") @Table(name="article")
 */
class Article
{
    /**
     * @Id @Column(type="integer") @GeneratedValue
     */
    protected $id;
    
    /**
     * @Column(type="string")
     */
    protected $title;
    
    /**
     * @Column(type="string")
     */
    protected $content;
    
    public function toArray()
    {
        return array("id" => $this->id,
                     "title" => $this->title,
                     "content" => $this->content);
    }
    
    public function fromArray($atributes)
    {
        $this->setTitle($atributes["title"]); 
        $this->setContent($atributes["content"]); 
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent($content)
    {
        $this->content = $content;
    }

}

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends Doctrine\ORM\EntityRepository
{
}
